<?php
return [
    ["quote" => "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author" => "Winston Churchill"],
    ["quote" => "The way to get started is to quit talking and begin doing.", "author" => "Walt Disney"],
    ["quote" => "Don't be afraid to give up the good to go for the great.", "author" => "John D. Rockefeller"],
    ["quote" => "Innovation distinguishes between a leader and a follower.", "author" => "Steve Jobs"],
    ["quote" => "The future belongs to those who believe in the beauty of their dreams.", "author" => "Eleanor Roosevelt"],
    ["quote" => "It is during our darkest moments that we must focus to see the light.", "author" => "Aristotle"],
    ["quote" => "The only way to do great work is to love what you do.", "author" => "Steve Jobs"],
    ["quote" => "If you really look closely, most overnight successes took a long time.", "author" => "Steve Jobs"],
    ["quote" => "Your limitation—it's only your imagination.", "author" => "Unknown"],
    ["quote" => "Great things never come from comfort zones.", "author" => "Unknown"],
    ["quote" => "Dream it. Wish it. Do it.", "author" => "Unknown"],
    ["quote" => "Success doesn't just find you. You have to go out and get it.", "author" => "Unknown"],
    ["quote" => "The harder you work for something, the greater you'll feel when you achieve it.", "author" => "Unknown"],
    ["quote" => "Dream bigger. Do bigger.", "author" => "Unknown"],
    ["quote" => "Don't stop when you're tired. Stop when you're done.", "author" => "Unknown"],
    ["quote" => "Wake up with determination. Go to bed with satisfaction.", "author" => "Unknown"],
    ["quote" => "Do something today that your future self will thank you for.", "author" => "Sean Patrick Flanery"],
    ["quote" => "Little things make big days.", "author" => "Unknown"],
    ["quote" => "It's going to be hard, but hard does not mean impossible.", "author" => "Unknown"],
    ["quote" => "Don't wait for opportunity. Create it.", "author" => "Unknown"],
    ["quote" => "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", "author" => "Unknown"],
    ["quote" => "The key to success is to focus on goals, not obstacles.", "author" => "Unknown"],
    ["quote" => "Dream it. Believe it. Build it.", "author" => "Unknown"],
    ["quote" => "What defines us is how well we rise after falling.", "author" => "Unknown"],
    ["quote" => "The only impossible journey is the one you never begin.", "author" => "Tony Robbins"],
    ["quote" => "In the middle of difficulty lies opportunity.", "author" => "Albert Einstein"],
    ["quote" => "The future depends on what you do today.", "author" => "Mahatma Gandhi"],
    ["quote" => "It's not about perfect. It's about effort.", "author" => "Unknown"],
    ["quote" => "Excellence is not a skill. It's an attitude.", "author" => "Ralph Marston"],
    ["quote" => "Focus on your goal. Don't look in any direction but ahead.", "author" => "Unknown"],
    ["quote" => "You don't get what you wish for. You get what you work for.", "author" => "Unknown"],
    ["quote" => "Dreams don't work unless you do.", "author" => "John C. Maxwell"],
    ["quote" => "Go the extra mile. It's never crowded.", "author" => "Wayne Dyer"],
    ["quote" => "Success is walking from failure to failure with no loss of enthusiasm.", "author" => "Winston Churchill"],
    ["quote" => "The only place where success comes before work is in the dictionary.", "author" => "Vidal Sassoon"],
    ["quote" => "There are no shortcuts to any place worth going.", "author" => "Beverly Sills"],
    ["quote" => "I find that the harder I work, the more luck I seem to have.", "author" => "Thomas Jefferson"],
    ["quote" => "Success is the sum of small efforts repeated day in and day out.", "author" => "Robert Collier"],
    ["quote" => "The secret of getting ahead is getting started.", "author" => "Mark Twain"],
    ["quote" => "Don't watch the clock; do what it does. Keep going.", "author" => "Sam Levenson"],
    ["quote" => "A year from now you may wish you had started today.", "author" => "Karen Lamb"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "Your only limit is your mind.", "author" => "Unknown"],
    ["quote" => "Push yourself, because no one else is going to do it for you.", "author" => "Unknown"],
    ["quote" => "Sometimes later becomes never. Do it now.", "author" => "Unknown"],
    ["quote" => "Great things happen to those who don't stop believing, trying, learning, and being grateful.", "author" => "Roy T. Bennett"],
    ["quote" => "If you want to achieve greatness stop asking for permission.", "author" => "Anonymous"],
    ["quote" => "Things work out best for those who make the best of how things work out.", "author" => "John Wooden"],
    ["quote" => "To live a creative life, we must lose our fear of being wrong.", "author" => "Joseph Chilton Pearce"],
    ["quote" => "If you are not willing to risk the usual you will have to settle for the ordinary.", "author" => "Jim Rohn"],
    ["quote" => "Trust because you are willing to accept the risk, not because it's safe or certain.", "author" => "Anonymous"],
    ["quote" => "Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea.", "author" => "Swami Vivekananda"],
    ["quote" => "All our dreams can come true if we have the courage to pursue them.", "author" => "Walt Disney"],
    ["quote" => "Good things happen to those who work hard.", "author" => "Anonymous"],
    ["quote" => "Don't stop until you're proud.", "author" => "Anonymous"],
    ["quote" => "Work hard in silence, let your success be the noise.", "author" => "Frank Ocean"],
    ["quote" => "The difference between ordinary and extraordinary is that little extra.", "author" => "Jimmy Johnson"],
    ["quote" => "The successful warrior is the average man with laser-like focus.", "author" => "Bruce Lee"],
    ["quote" => "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", "author" => "Dale Carnegie"],
    ["quote" => "If you don't design your own life plan, chances are you'll fall into someone else's plan.", "author" => "Jim Rohn"],
    ["quote" => "The question isn't who is going to let me; it's who is going to stop me.", "author" => "Ayn Rand"],
    ["quote" => "You are never too old to set another goal or to dream a new dream.", "author" => "C.S. Lewis"],
    ["quote" => "Try not to become a person of success, but rather try to become a person of value.", "author" => "Albert Einstein"],
    ["quote" => "It is not the strongest of the species that survives, but the one that is the most adaptable to change.", "author" => "Charles Darwin"],
    ["quote" => "Great minds discuss ideas; average minds discuss events; small minds discuss people.", "author" => "Eleanor Roosevelt"],
    ["quote" => "I have not failed. I've just found 10,000 ways that won't work.", "author" => "Thomas Edison"],
    ["quote" => "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", "author" => "David Brinkley"],
    ["quote" => "No one can make you feel inferior without your consent.", "author" => "Eleanor Roosevelt"],
    ["quote" => "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author" => "Nelson Mandela"],
    ["quote" => "Life is what happens to you while you're busy making other plans.", "author" => "John Lennon"],
    ["quote" => "Whoever is happy will make others happy too.", "author" => "Anne Frank"],
    ["quote" => "Life is really simple, but we insist on making it complicated.", "author" => "Confucius"],
    ["quote" => "May you live all the days of your life.", "author" => "Jonathan Swift"],
    ["quote" => "Life itself is the most wonderful fairy tale.", "author" => "Hans Christian Andersen"],
    ["quote" => "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "In the end, it's not the years in your life that count. It's the life in your years.", "author" => "Abraham Lincoln"],
    ["quote" => "Life is a succession of lessons which must be lived to be understood.", "author" => "Helen Keller"],
    ["quote" => "You have within you right now, everything you need to deal with whatever the world can throw at you.", "author" => "Brian Tracy"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Change your thoughts and you change your world.", "author" => "Norman Vincent Peale"],
    ["quote" => "Either write something worth reading or do something worth writing.", "author" => "Benjamin Franklin"],
    ["quote" => "Nothing is impossible, the word itself says, 'I'm possible!'", "author" => "Audrey Hepburn"],
    ["quote" => "If you can dream it, you can achieve it.", "author" => "Zig Ziglar"],
    ["quote" => "Where there is a will, there is a way.", "author" => "English Proverb"],
    ["quote" => "Strive not to be a success, but rather to be of value.", "author" => "Albert Einstein"],
    ["quote" => "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", "author" => "Robert Frost"],
    ["quote" => "I attribute my success to this: I never gave or took any excuse.", "author" => "Florence Nightingale"],
    ["quote" => "You miss 100% of the shots you don't take.", "author" => "Wayne Gretzky"],
    ["quote" => "The most difficult thing is the decision to act, the rest is merely tenacity.", "author" => "Amelia Earhart"],
    ["quote" => "Every strike brings me closer to the next home run.", "author" => "Babe Ruth"],
    ["quote" => "Definite purpose and a burning desire to fulfill that purpose.", "author" => "Napoleon Hill"],
    ["quote" => "Life isn't about getting and having, it's about giving and being.", "author" => "Kevin Kruse"],
    ["quote" => "Life is what we make it, always has been, always will be.", "author" => "Grandma Moses"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Everything you've ever wanted is on the other side of fear.", "author" => "George Addair"],
    ["quote" => "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "author" => "Plato"],
    ["quote" => "Teach thy tongue to say, 'I do not know,' and thou shalt progress.", "author" => "Maimonides"],
    ["quote" => "Start where you are. Use what you have. Do what you can.", "author" => "Arthur Ashe"],
    ["quote" => "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "author" => "John Lennon"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "author" => "Helen Keller"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Everything you've ever wanted is on the other side of fear.", "author" => "George Addair"],
    ["quote" => "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "author" => "Plato"],
    ["quote" => "Teach thy tongue to say, 'I do not know,' and thou shalt progress.", "author" => "Maimonides"],
    ["quote" => "Start where you are. Use what you have. Do what you can.", "author" => "Arthur Ashe"],
    ["quote" => "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "author" => "John Lennon"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "author" => "Helen Keller"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Everything you've ever wanted is on the other side of fear.", "author" => "George Addair"],
    ["quote" => "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "author" => "Plato"],
    ["quote" => "Teach thy tongue to say, 'I do not know,' and thou shalt progress.", "author" => "Maimonides"],
    ["quote" => "Start where you are. Use what you have. Do what you can.", "author" => "Arthur Ashe"],
    ["quote" => "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "author" => "John Lennon"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "author" => "Helen Keller"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Everything you've ever wanted is on the other side of fear.", "author" => "George Addair"],
    ["quote" => "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "author" => "Plato"],
    ["quote" => "Teach thy tongue to say, 'I do not know,' and thou shalt progress.", "author" => "Maimonides"],
    ["quote" => "Start where you are. Use what you have. Do what you can.", "author" => "Arthur Ashe"],
    ["quote" => "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "author" => "John Lennon"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "author" => "Helen Keller"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
    ["quote" => "Believe you can and you're halfway there.", "author" => "Theodore Roosevelt"],
    ["quote" => "Everything you've ever wanted is on the other side of fear.", "author" => "George Addair"],
    ["quote" => "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", "author" => "Plato"],
    ["quote" => "Teach thy tongue to say, 'I do not know,' and thou shalt progress.", "author" => "Maimonides"],
    ["quote" => "Start where you are. Use what you have. Do what you can.", "author" => "Arthur Ashe"],
    ["quote" => "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life.", "author" => "John Lennon"],
    ["quote" => "Fall seven times and stand up eight.", "author" => "Japanese Proverb"],
    ["quote" => "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", "author" => "Helen Keller"],
    ["quote" => "Everything has beauty, but not everyone can see.", "author" => "Confucius"],
    ["quote" => "How wonderful it is that nobody need wait a single moment before starting to improve the world.", "author" => "Anne Frank"],
    ["quote" => "When I let go of what I am, I become what I might be.", "author" => "Lao Tzu"],
    ["quote" => "Life is 10% what happens to me and 90% of how I react to it.", "author" => "Charles R. Swindoll"],
    ["quote" => "The most common way people give up their power is by thinking they don't have any.", "author" => "Alice Walker"],
    ["quote" => "The mind is everything. What you think you become.", "author" => "Buddha"],
    ["quote" => "The best time to plant a tree was 20 years ago. The second best time is now.", "author" => "Chinese Proverb"],
    ["quote" => "An unexamined life is not worth living.", "author" => "Socrates"],
    ["quote" => "Eighty percent of success is showing up.", "author" => "Woody Allen"],
    ["quote" => "Your time is limited, so don't waste it living someone else's life.", "author" => "Steve Jobs"],
    ["quote" => "Winning isn't everything, but wanting to win is.", "author" => "Vince Lombardi"],
    ["quote" => "I am not a product of my circumstances. I am a product of my decisions.", "author" => "Stephen R. Covey"],
    ["quote" => "Every child is an artist. The problem is how to remain an artist once we grow up.", "author" => "Pablo Picasso"],
    ["quote" => "You can never cross the ocean until you have the courage to lose sight of the shore.", "author" => "Christopher Columbus"],
    ["quote" => "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", "author" => "Maya Angelou"],
    ["quote" => "Either you run the day, or the day runs you.", "author" => "Jim Rohn"],
    ["quote" => "Whether you think you can or you think you can't, you're right.", "author" => "Henry Ford"],
    ["quote" => "The two most important days in your life are the day you are born and the day you find out why.", "author" => "Mark Twain"],
    ["quote" => "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "author" => "Johann Wolfgang von Goethe"],
    ["quote" => "The best revenge is massive success.", "author" => "Frank Sinatra"],
    ["quote" => "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", "author" => "Zig Ziglar"],
    ["quote" => "Life shrinks or expands in proportion to one's courage.", "author" => "Anais Nin"],
    ["quote" => "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced.", "author" => "Vincent Van Gogh"],
    ["quote" => "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author" => "Aristotle"],
    ["quote" => "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", "author" => "Jesus"],
    ["quote" => "The only person you are destined to become is the person you decide to be.", "author" => "Ralph Waldo Emerson"],
    ["quote" => "Go confidently in the direction of your dreams. Live the life you have imagined.", "author" => "Henry David Thoreau"],
    ["quote" => "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", "author" => "Erma Bombeck"],
    ["quote" => "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", "author" => "Booker T. Washington"],
    ["quote" => "Certain things catch your eye, but pursue only those that capture the heart.", "author" => "Ancient Indian Proverb"],
];
