@php
$motivationalQuotes = [
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "Innovation distinguishes between a leader and a follower.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is during our darkest moments that we must focus to see the light.",
    "The only way to do great work is to love what you do.",
    "If you really look closely, most overnight successes took a long time.",
    "Your limitation—it's only your imagination.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "What defines us is how well we rise after falling.",
    "The only impossible journey is the one you never begin.",
    "In the middle of difficulty lies opportunity.",
    "The future depends on what you do today.",
    "It's not about perfect. It's about effort.",
    "Excellence is not a skill. It's an attitude.",
    "Focus on your goal. Don't look in any direction but ahead.",
    "You don't get what you wish for. You get what you work for.",
    "Dreams don't work unless you do.",
    "Go the extra mile. It's never crowded.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only place where success comes before work is in the dictionary.",
    "There are no shortcuts to any place worth going.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "Innovation distinguishes between a leader and a follower.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is during our darkest moments that we must focus to see the light.",
    "The only way to do great work is to love what you do.",
    "If you really look closely, most overnight successes took a long time.",
    "Your limitation—it's only your imagination.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "What defines us is how well we rise after falling.",
    "The only impossible journey is the one you never begin.",
    "In the middle of difficulty lies opportunity.",
    "The future depends on what you do today.",
    "It's not about perfect. It's about effort.",
    "Excellence is not a skill. It's an attitude.",
    "Focus on your goal. Don't look in any direction but ahead.",
    "You don't get what you wish for. You get what you work for.",
    "Dreams don't work unless you do.",
    "Go the extra mile. It's never crowded.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only place where success comes before work is in the dictionary.",
    "There are no shortcuts to any place worth going.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is the sum of small efforts repeated day in and day out.",
    "The way to get started is to quit talking and begin doing.",
    "Don't be afraid to give up the good to go for the great.",
    "Innovation distinguishes between a leader and a follower.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It is during our darkest moments that we must focus to see the light.",
    "The only way to do great work is to love what you do.",
    "If you really look closely, most overnight successes took a long time.",
    "Your limitation—it's only your imagination.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "What defines us is how well we rise after falling.",
    "The only impossible journey is the one you never begin.",
    "In the middle of difficulty lies opportunity.",
    "The future depends on what you do today.",
    "It's not about perfect. It's about effort.",
    "Excellence is not a skill. It's an attitude.",
    "Focus on your goal. Don't look in any direction but ahead.",
    "You don't get what you wish for. You get what you work for.",
    "Dreams don't work unless you do.",
    "Go the extra mile. It's never crowded.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only place where success comes before work is in the dictionary.",
    "There are no shortcuts to any place worth going.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is the sum of small efforts repeated day in and day out."
];
@endphp
